### ISSUE TITLE
Adding link to HTML5 banner / video banner? 

### ISSUE THREAD

**Issue by serhanni** [giuliopons/adadmin#64]
How can I add link to HTML5 banner?

There is no link input at HTML5 tab like shown as [this picture](https://www.barattalo.it/wp-content/uploads/2022/01/image-1024x558.png)

I followed both https://www.barattalo.it/tools/adadmin-video-banner-examples/ and https://github.com/giuliopons/adadmin/discussions/58 but couldn't find the way.

For example; in your admin demo,
https://www.barattalo.it/ambdemo/ser.php?test_id=53 was pointing to codecanyon
I downloaded the backup of banner 53_0.zip
I removed the html5 banner
I reupload the 53_0.zip

Now, the banner link points to https://www.barattalo.it

### Discussed in https://github.com/giuliopons/adadmin/discussions/58

<div type='discussions-op-text'>

<sup>Originally posted by **giuliopons** December 11, 2022</sup>
</div>

**Comment by serhanni** [comment]
Changing `$('#linkbox').addClass("close");` to `$('#linkbox').removeClass("close");` in dettaglio.js is solved my problem.

**Comment by giuliopons** [comment]
Thankyou you found a bug.
In HTML5 banner you must put the clicktag inside your html code.
The clicktag counts the click and redirect to the final link. The bug is
that you can't add the link in html5 banner .
I'm going to add this fix in the next version .
Giulio



Il lun 3 apr 2023, 16:50 serhanni ***@***.***> ha scritto:

**Comment by giuliopons** [comment]
Next version will include this fix

**Comment by giuliopons** [comment]
fixed in v.4.0.0
